<?php
/**
 * Template Creator
 *
 * Creates custom page template files in the active theme from WP Admin.
 * No FTP or code editor required.
 *
 * How it works:
 * 1. User enters a template name e.g. "Landing Page"
 * 2. Plugin creates template-landing-page.php in the active theme
 * 3. Template immediately appears in WP Page editor under Page Attributes
 */

add_action( 'admin_init', 'techark_handle_template_creator' );

function techark_handle_template_creator() {

	if ( ! isset( $_POST['techark_create_template'] ) ) {
		return;
	}

	if ( ! current_user_can( 'manage_options' ) ) {
		wp_die( 'Unauthorized' );
	}

	check_admin_referer( 'techark_template_creator' );

	$template_name = sanitize_text_field( $_POST['template_name'] ?? '' );
	$template_desc = sanitize_text_field( $_POST['template_desc'] ?? '' );

	if ( empty( $template_name ) ) {
		wp_redirect( admin_url( 'admin.php?page=techark-template-creator&error=missing_name' ) );
		exit;
	}

	// Generate filename from template name
	$template_slug = sanitize_title( $template_name );
	$filename      = 'template-' . $template_slug . '.php';
	$theme_dir     = get_template_directory();
	$file_path     = $theme_dir . '/' . $filename;

	// Don't overwrite existing templates
	if ( file_exists( $file_path ) ) {
		wp_redirect( admin_url( 'admin.php?page=techark-template-creator&error=already_exists&file=' . urlencode( $filename ) ) );
		exit;
	}

	// Template file content
	$description = ! empty( $template_desc ) ? $template_desc : $template_name . ' page template.';
	$content     = '<?php' . PHP_EOL;
	$content    .= '/**' . PHP_EOL;
	$content    .= ' * Template Name: ' . $template_name . PHP_EOL;
	$content    .= ' * Description:   ' . $description . PHP_EOL;
	$content    .= ' *' . PHP_EOL;
	$content    .= ' * Generated by TechArk Theme Builder' . PHP_EOL;
	$content    .= ' */' . PHP_EOL;
	$content    .= PHP_EOL;
	$content    .= 'get_header();' . PHP_EOL;
	$content    .= '?>' . PHP_EOL;
	$content    .= PHP_EOL;
	$content    .= '<main id="primary" class="site-main">' . PHP_EOL;
	$content    .= PHP_EOL;
	$content    .= "\t" . '<?php' . PHP_EOL;
	$content    .= "\t" . '// Add your custom template content here' . PHP_EOL;
	$content    .= "\t" . 'if ( have_posts() ) :' . PHP_EOL;
	$content    .= "\t\t" . 'while ( have_posts() ) :' . PHP_EOL;
	$content    .= "\t\t\t" . 'the_post();' . PHP_EOL;
	$content    .= "\t\t\t" . 'the_content();' . PHP_EOL;
	$content    .= "\t\t" . 'endwhile;' . PHP_EOL;
	$content    .= "\t" . 'endif;' . PHP_EOL;
	$content    .= "\t" . '?>' . PHP_EOL;
	$content    .= PHP_EOL;
	$content    .= '</main>' . PHP_EOL;
	$content    .= PHP_EOL;
	$content    .= '<?php' . PHP_EOL;
	$content    .= 'get_footer();' . PHP_EOL;

	// Write file
	$result = file_put_contents( $file_path, $content );

	if ( $result === false ) {
		wp_redirect( admin_url( 'admin.php?page=techark-template-creator&error=write_failed' ) );
		exit;
	}

	wp_redirect( admin_url( 'admin.php?page=techark-template-creator&success=1&file=' . urlencode( $filename ) ) );
	exit;
}

/**
 * Template Creator page HTML
 */
function techark_template_creator_page() {

	$error   = $_GET['error'] ?? '';
	$success = $_GET['success'] ?? '';
	$file    = $_GET['file'] ?? '';

	// List existing custom templates in active theme
	$theme_dir = get_template_directory();
	$templates = glob( $theme_dir . '/template-*.php' ) ?: array();
	?>
	<div class="wrap">
		<h1>📄 Template Creator</h1>
		<p class="description">Create a new page template in the active theme. It will appear immediately in WP Page editor under Page Attributes → Template.</p>

		<?php if ( $success ) : ?>
			<div class="notice notice-success">
				<p><strong>✓ Template created successfully!</strong> File: <code><?php echo esc_html( $file ); ?></code></p>
				<p>Go to <a href="<?php echo esc_url( admin_url( 'post-new.php?post_type=page' ) ); ?>">Pages → Add New</a> and check Page Attributes → Template to see it.</p>
			</div>
		<?php elseif ( $error === 'missing_name' ) : ?>
			<div class="notice notice-error"><p><strong>Error:</strong> Template name is required.</p></div>
		<?php elseif ( $error === 'already_exists' ) : ?>
			<div class="notice notice-error"><p><strong>Error:</strong> Template file <code><?php echo esc_html( $file ); ?></code> already exists. Choose a different name.</p></div>
		<?php elseif ( $error === 'write_failed' ) : ?>
			<div class="notice notice-error"><p><strong>Error:</strong> Could not write file. Check theme directory permissions.</p></div>
		<?php endif; ?>

		<div style="max-width:600px;margin-top:20px;">
			<form method="post" action="<?php echo esc_url( admin_url( 'admin.php?page=techark-template-creator' ) ); ?>">
				<?php wp_nonce_field( 'techark_template_creator' ); ?>
				<input type="hidden" name="techark_create_template" value="1">

				<table class="form-table">
					<tr>
						<th><label for="template_name">Template Name <span style="color:red">*</span></label></th>
						<td>
							<input type="text" id="template_name" name="template_name" class="regular-text" placeholder="Landing Page" required>
							<p class="description">This is the name shown in WP Page editor. e.g. "Landing Page", "Full Width", "No Sidebar"</p>
						</td>
					</tr>
					<tr>
						<th><label for="template_desc">Description</label></th>
						<td>
							<input type="text" id="template_desc" name="template_desc" class="regular-text" placeholder="Custom landing page template without sidebar.">
						</td>
					</tr>
					<tr>
						<th>Generated filename</th>
						<td>
							<code id="preview_filename">template-landing-page.php</code>
							<p class="description">Auto-generated from template name. File is created in the active theme folder.</p>
						</td>
					</tr>
				</table>

				<?php submit_button( '+ Create Template', 'primary' ); ?>
			</form>
		</div>

		<?php if ( ! empty( $templates ) ) : ?>
			<div style="max-width:600px;margin-top:30px;">
				<h2>Existing Custom Templates</h2>
				<table class="widefat striped" style="margin-top:10px;">
					<thead>
						<tr>
							<th>File</th>
							<th>Template Name</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ( $templates as $tpl ) :
							$tpl_data = get_file_data( $tpl, array( 'name' => 'Template Name' ) );
							?>
							<tr>
								<td><code><?php echo esc_html( basename( $tpl ) ); ?></code></td>
								<td><?php echo esc_html( $tpl_data['name'] ?: '—' ); ?></td>
							</tr>
						<?php endforeach; ?>
					</tbody>
				</table>
			</div>
		<?php endif; ?>
	</div>

	<script>
	document.getElementById('template_name').addEventListener('input', function() {
		const name = this.value;
		const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
		document.getElementById('preview_filename').textContent = slug ? 'template-' + slug + '.php' : 'template-landing-page.php';
	});
	</script>
	<?php
}
