name: WordPress Theme CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  php-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate PHP Files
        run: find . -name "*.php" -exec php -l {} \;